repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: ["--follow-imports=skip", "--ignore-missing-imports", "--disable-error-code","attr-defined"]

  - repo: https://github.com/psf/black
    rev: "24.2.0"
    hooks:
      - id: black
        args: ["--line-length", "120"]

  - repo: https://github.com/PyCQA/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1"
    hooks:
      - id: isort
        args: ["--profile", "black"]
